on: [push]

jobs:
  python-test:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/devcontainers/python:3.9
    steps:
      - name: Configure git to trust the workspace despite the different owner
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.1
      - name: Install dependencies
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make vtest
