on: [push]

jobs:
  python-test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/python:3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --no-cache-dir "poetry==$POETRY_VERSION"
          make install
        env:
          POETRY_VERSION: 1.2.1
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
